### ISSUE TITLE
Specify explicit version of mathlib in lakefile

### ISSUE THREAD

**Issue by tonyxty** [avigad/mathematics_in_lean_source#184]
... so that builds are not affected by changes in mathlib.

**Comment by PatrickMassot** [comment]
Thanks for your comment. If you think this is an issue then it means you’re doing something wrong. Changes already have no impact. The precise version of Mathlib is stored in the `lake-manifest.json` file, not in `lakefile.lean`. Storing a commit hash in the lakefile of a project is useful only when you want to allow to fix one dependency version when running `lake update`. Here it wouldn’t make any sense since there is only one dependency. And users of mathematics in Lean never ever have to run `lake update` anyway (authors do, but only when they want changes in mathlib).
